services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=gerenciador_tb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gerenciador-tarefas-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      # Passa os segredos para o application-prod.properties
      - DB_USER=postgres
      - DB_PASSWORD=1234
      # Garante que o horário do container seja o do Brasil
      - TZ=America/Sao_Paulo

volumes:
  postgres-data: